restylers:
- enabled: true
  include: astyle-test-*
  name: astyle
- enabled: true
  include: autopep8-test-*
  name: autopep8
- enabled: true
  include: black-test-*
  name: black
- enabled: true
  include: brittany-test-*
  name: brittany
- enabled: true
  include: cabal-fmt-test-*
  name: cabal-fmt
- enabled: true
  include: clang-format-test-*
  name: clang-format
- enabled: true
  include: cmake-format-test-*
  name: cmake-format
- enabled: true
  include: dart-format-test-*
  name: dart-format
- enabled: true
  include: dfmt-test-*
  name: dfmt
- enabled: true
  include: dhall-format-test-*
  name: dhall-format
- enabled: true
  include: dotnet-format-test-*
  name: dotnet-format
- enabled: true
  include: elm-format-test-*
  name: elm-format
- enabled: true
  include: fantomas-test-*
  name: fantomas
- enabled: true
  include: fourmolu-test-*
  name: fourmolu
- enabled: true
  include: gn-test-*
  name: gn
- enabled: true
  include: gofmt-test-*
  name: gofmt
- enabled: true
  include: google-java-format-test-*
  name: google-java-format
- enabled: true
  include: hindent-test-*
  name: hindent
- enabled: true
  include: hlint-test-*
  name: hlint
- enabled: true
  include: isort-test-*
  name: isort
- enabled: true
  include: jdt-test-*
  name: jdt
- enabled: true
  include: jq-test-*
  name: jq
- enabled: true
  include: luaformatter-test-*
  name: luaformatter
- enabled: true
  include: nixpkgs-fmt-test-*
  name: nixpkgs-fmt
- enabled: true
  include: npm-groovy-lint-test-*
  name: npm-groovy-lint
- enabled: true
  include: ocamlformat-test-*
  name: ocamlformat
- enabled: true
  include: ormolu-test-*
  name: ormolu
- enabled: true
  include: perltidy-test-*
  name: perltidy
- enabled: true
  include: pg_format-test-*
  name: pg_format
- enabled: true
  include: php-cs-fixer-test-*
  name: php-cs-fixer
- enabled: true
  include: prettier-ruby-test-*
  name: prettier-ruby
- enabled: true
  include: prettier-test-*
  name: prettier
- enabled: true
  include: prettier-json-test-*
  name: prettier-json
- enabled: true
  include: prettier-markdown-test-*
  name: prettier-markdown
- enabled: true
  include: prettier-yaml-test-*
  name: prettier-yaml
- enabled: true
  include: purty-test-*
  name: purty
- enabled: true
  include: pyment-test-*
  name: pyment
- enabled: true
  include: refmt-test-*
  name: refmt
- enabled: true
  include: reorder-python-imports-test-*
  name: reorder-python-imports
- enabled: true
  include: rubocop-test-*
  name: rubocop
- enabled: true
  include: rustfmt-test-*
  name: rustfmt
- enabled: true
  include: scalafmt-test-*
  name: scalafmt
- enabled: true
  include: shellcheck-test-*
  name: shellcheck
- enabled: true
  include: shellharden-test-*
  name: shellharden
- enabled: true
  include: shfmt-test-*
  name: shfmt
- enabled: true
  include: sqlformat-test-*
  name: sqlformat
- enabled: true
  include: standardrb-test-*
  name: standardrb
- enabled: true
  include: stylish-haskell-test-*
  name: stylish-haskell
- enabled: true
  include: taplo-test-*
  name: taplo
- enabled: true
  include: terraform-test-*
  name: terraform
- enabled: true
  include: verible-test-*
  name: verible
- enabled: true
  include: whitespace-test-*
  name: whitespace
- enabled: true
  include: yapf-test-*
  name: yapf
restylers_version: dev
