restylers_version: stable
restylers:
- include: astyle/**/*
  enabled: true
  name: astyle
- include: autopep8/**/*
  enabled: true
  name: autopep8
- include: black/**/*
  enabled: true
  name: black
- include: brittany/**/*
  enabled: true
  name: brittany
- include: clang-format/**/*
  enabled: true
  name: clang-format
- include: dfmt/**/*
  enabled: true
  name: dfmt
- include: dhall-format/**/*
  enabled: true
  name: dhall-format
- include: dotnet-format/**/*
  enabled: true
  name: dotnet-format
- include: elm-format/**/*
  enabled: true
  name: elm-format
- include: fantomas/**/*
  enabled: true
  name: fantomas
- include: gn/**/*
  enabled: true
  name: gn
- include: gofmt/**/*
  enabled: true
  name: gofmt
- include: google-java-format/**/*
  enabled: true
  name: google-java-format
- include: hindent/**/*
  enabled: true
  name: hindent
- include: hlint/**/*
  enabled: true
  name: hlint
- include: isort/**/*
  enabled: true
  name: isort
- include: jdt/**/*
  enabled: true
  name: jdt
- include: jq/**/*
  enabled: true
  name: jq
- include: ormolu/**/*
  enabled: true
  name: ormolu
- include: pg_format/**/*
  enabled: true
  name: pg_format
- include: php-cs-fixer/**/*
  enabled: true
  name: php-cs-fixer
- include: prettier-json/**/*
  enabled: true
  name: prettier-json
- include: prettier-markdown/**/*
  enabled: true
  name: prettier-markdown
- include: prettier-ruby/**/*
  enabled: true
  name: prettier-ruby
- include: prettier-yaml/**/*
  enabled: true
  name: prettier-yaml
- include: prettier/**/*
  enabled: true
  name: prettier
- include: reorder-python-imports/**/*
  enabled: true
  name: reorder-python-imports
- include: rubocop/**/*
  enabled: true
  name: rubocop
- include: rustfmt/**/*
  enabled: true
  name: rustfmt
- include: shellharden/**/*
  enabled: true
  name: shellharden
- include: shfmt/**/*
  enabled: true
  name: shfmt
- include: stylish-haskell/**/*
  enabled: true
  name: stylish-haskell
- include: terraform/**/*
  enabled: true
  name: terraform
- include: whitespace/**/*
  enabled: true
  name: whitespace
- include: yapf/**/*
  enabled: true
  name: yapf
