restylers:
- enabled: true
  include: astyle/**/*
  name: astyle
- enabled: true
  include: autopep8/**/*
  name: autopep8
- enabled: true
  include: black/**/*
  name: black
- enabled: true
  include: brittany/**/*
  name: brittany
- enabled: true
  include: clang-format/**/*
  name: clang-format
- enabled: true
  include: dfmt/**/*
  name: dfmt
- enabled: true
  include: dhall-format/**/*
  name: dhall-format
- enabled: true
  include: dotnet-format/**/*
  name: dotnet-format
- enabled: true
  include: elm-format/**/*
  name: elm-format
- enabled: true
  include: fantomas/**/*
  name: fantomas
- enabled: true
  include: fourmolu/**/*
  name: fourmolu
- enabled: true
  include: gn/**/*
  name: gn
- enabled: true
  include: gofmt/**/*
  name: gofmt
- enabled: true
  include: google-java-format/**/*
  name: google-java-format
- enabled: true
  include: hindent/**/*
  name: hindent
- enabled: true
  include: hlint/**/*
  name: hlint
- enabled: true
  include: isort/**/*
  name: isort
- enabled: true
  include: jdt/**/*
  name: jdt
- enabled: true
  include: jq/**/*
  name: jq
- enabled: true
  include: luaformatter/**/*
  name: luaformatter
- enabled: true
  include: nixpkgs-fmt/**/*
  name: nixpkgs-fmt
- enabled: true
  include: npm-groovy-lint/**/*
  name: npm-groovy-lint
- enabled: true
  include: ormolu/**/*
  name: ormolu
- enabled: true
  include: pg_format/**/*
  name: pg_format
- enabled: true
  include: php-cs-fixer/**/*
  name: php-cs-fixer
- enabled: true
  include: prettier-ruby/**/*
  name: prettier-ruby
- enabled: true
  include: prettier/**/*
  name: prettier
- enabled: true
  include: prettier-json/**/*
  name: prettier-json
- enabled: true
  include: prettier-markdown/**/*
  name: prettier-markdown
- enabled: true
  include: prettier-yaml/**/*
  name: prettier-yaml
- enabled: true
  include: reorder-python-imports/**/*
  name: reorder-python-imports
- enabled: true
  include: rubocop/**/*
  name: rubocop
- enabled: true
  include: rustfmt/**/*
  name: rustfmt
- enabled: true
  include: shellcheck/**/*
  name: shellcheck
- enabled: true
  include: shellharden/**/*
  name: shellharden
- enabled: true
  include: shfmt/**/*
  name: shfmt
- enabled: true
  include: sqlformat/**/*
  name: sqlformat
- enabled: true
  include: standardrb/**/*
  name: standardrb
- enabled: true
  include: stylish-haskell/**/*
  name: stylish-haskell
- enabled: true
  include: terraform/**/*
  name: terraform
- enabled: true
  include: verible/**/*
  name: verible
- enabled: true
  include: whitespace/**/*
  name: whitespace
- enabled: true
  include: yapf/**/*
  name: yapf
restylers_version: dev
